export default [
  { curso: 'Administração' },
  { curso: 'Agronomia' },
  { curso: 'Análise e Desenvolvimento de Sistemas' },
  { curso: 'Arquitetura e Urbanismo' },
  { curso: 'Artes Visuais' },
  { curso: 'Automação Industrial' },
  { curso: 'Biomedicina' },
  { curso: 'Ciências Biológicas' },
  { curso: 'Ciências Contábeis' },
  { curso: 'Comércio Exterior' },
  { curso: 'Design de Interiores' },
  { curso: 'Direito' },
  { curso: 'Educação Física' },
  { curso: 'Enfermagem' },
  { curso: 'Engenharia Ambiental e Sanitária' },
  { curso: 'Engenharia Civil' },
  { curso: 'Engenharia de Produção' },
  { curso: 'Engenharia de Software' },
  { curso: 'Engenharia Elétrica' },
  { curso: 'Engenharia Mecânica' },
  { curso: 'Engenharia Mecatrônica' },
  { curso: 'Engenharia Química' },
  { curso: 'Estética e Cosmética' },
  { curso: 'Farmácia' },
  { curso: 'Fisioterapia' },
  { curso: 'Fonoaudiologia' },
  { curso: 'Gastronomia' },
  { curso: 'Gestão de Recursos Humanos' },
  { curso: 'Jornalismo' },
  { curso: 'Medicina' },
  { curso: 'Medicina Veterinária' },
  { curso: 'Moda' },
  { curso: 'Música' },
  { curso: 'Nutrição' },
  { curso: 'Odontologia' },
  { curso: 'Pedagogia' },
  { curso: 'Pilotagem Profissional de Aeronaves' },
  { curso: 'Processos Gerenciais' },
  { curso: 'Psicologia' },
  { curso: 'Publicidade e Propaganda' },
  { curso: 'Redes de Computadores' },
];
